Add "Getting Started" lab to introduce Terraform concepts
terraform-google-modules/cloud-foundation-training pull request #10
Opened 2020-02-20 02:05 UTC by zefdelgadillo

The 01-getting-started lab aims to introduce Terraform concepts for users/students who may have not used the tool before. It also walks through the general lab flow to get users familiar with running Terraform commands.

2020-02-20 02:06 UTC, zefdelgadillo commented
@bharathkkb as another reviewer

2020-02-20 06:30 UTC, bharathkkb requested changes

2020-02-20 06:30 UTC, bharathkkb commented on 06-Cloud-Function/README.md
> +<<<<<<< HEAD:05-Cloud-Function/README.md
Conflict markers in this file

2020-02-20 15:57 UTC, zefdelgadillo commented on 06-Cloud-Function/README.md
> +<<<<<<< HEAD:05-Cloud-Function/README.md
Thanks for the catch

2020-02-20 21:33 UTC, bharathkkb approved these changes

2020-02-20 23:12 UTC, zefdelgadillo commented
@marine675 can you also take a look when you have some time?

2020-02-21 04:52 UTC, marine675 requested changes

2020-02-21 04:52 UTC, marine675 commented on 01-Getting-Started/README.md
> +At the end of the exercise, you will have 2 GCS buckets (**Logs** and **Remote State**) with 4 lines of output value.
Where are the `output` blocks?

2020-02-21 04:52 UTC, marine675 commented on 01-Getting-Started/README.md
> +At the end of the exercise, you will have 2 GCS buckets (**Logs** and **Remote State**) with 4 lines of output value.
Only seeing 1 GCS bucket for remote state

2020-02-21 18:08 UTC, zefdelgadillo commented on 01-Getting-Started/README.md
> +At the end of the exercise, you will have 2 GCS buckets (**Logs** and **Remote State**) with 4 lines of output value.
I opted for just a single GCS bucket for state to isolate and must have missed this part of the documentation. I'll clean it up.

Output block is a good idea for instruction also as part of getting-started.

2020-02-21 18:25 UTC, zefdelgadillo commented on 01-Getting-Started/README.md
> +At the end of the exercise, you will have 2 GCS buckets (**Logs** and **Remote State**) with 4 lines of output value.
cebadab should take care of this

2020-02-23 03:21 UTC, marine675 approved these changes
LGTM

2020-02-23 03:22 UTC, merged